# Generated by Django 5.1.2 on 2024-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='electric_windows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_doors',
            field=models.IntegerField(choices=[(2, '2 portas'), (3, '3 portas'), (4, '4 portas')], default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='power_steering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático')], default='Manual', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='trunk_electric',
            field=models.BooleanField(default=False),
        ),
    ]
