# Generated by Django 5.1.2 on 2024-10-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
